### ISSUE TITLE
com.intellij.serviceContainer.AlreadyDisposedException

### ISSUE THREAD

**Issue by Klaus-Kin** [veezean/IntellijIDEA-CodeReview-Plugin#9]
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.psi.search.PsiShortNamesCache because container is already disposed (container=Project(name=packed-token-service, containerState=DISPOSE_COMPLETED, componentStore=E:\workspace\idea\MiGu\packed-token-service) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:34)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:631)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:583)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.psi.search.PsiShortNamesCache.getInstance(PsiShortNamesCache.java:29)
	at com.veezean.idea.plugin.codereviewer.action.ManageReviewCommentUI.doubleClickDumpToOriginal(ManageReviewCommentUI.java:272)
	at com.veezean.idea.plugin.codereviewer.action.ManageReviewCommentUI.access$300(ManageReviewCommentUI.java:44)
	at com.veezean.idea.plugin.codereviewer.action.ManageReviewCommentUI$2.mouseClicked(ManageReviewCommentUI.java:238)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4584)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by monkeyKinn** [comment]
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Licensed to Ronghan Liu
订阅有效期至 2023年5月23日。
For educational use only.
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.watches.in.variables=false
    documentation.show.toolbar=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    org.ermadan.kafkalytic (0.10.5)
    emacsIDEAs (1.4.9)
    de.netnexus.camelcaseplugin (3.0.12)
    com.notime.intellijPlugin.backgroundImagePlus (1.0.3)
    com.nasller.CodeGlancePro (1.4.6)
    com.markskelton.one-dark-theme (5.6.0)
    com.intellij.zh (222.168)
    org.intellij.plugins.junitgen (2.0.12)
    com.yangchenwen.sqlparamssetter (1.1)
    com.veezean.idea.plugin.codereviewer (2.4)
    com.nnthink.aixcoder (4.0.3-2020)
    com.jetbrains.jax.ws (222.3345.118)
    com.intellij.guice (222.3345.118)
    com-cs-org (2022.1.9)
    Statistic (4.1.10)
    HighlightBracketPair (1.3.6)
    GrepConsole (12.14.211.6693.0)
    org.sonarlint.idea (6.8.0.50884)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (65.1.0)
    PlantUML integration (5.16.1)
    GenerateSerialVersionUID (3.0.3)
    com.intellij.kubernetes (222.3345.108)
    io.github.newhoo.restkit (2.0.6)
    SequenceDiagram (2.2.0)
    MavenRunHelper (4.20.213.3714.1)
    JRebelPlugin (2022.3.0)
    org.intellij.scala (2022.2.10)
    com.intellij.bigdatatools (222.3345.30)
    izhangzhihao.rainbow.brackets (6.25)
    com.ccnode.codegenerator.MyBatisCodeHelperPro (3.0.6)
    com.bruce.intellijplugin.generatesetter (2.8.1)
    cn.yiiguxing.plugin.translate (3.3.4)
    MetricsReloaded (1.12)

Kotlin: 222-1.7.10-release-334-IJ3345.118

**Comment by Klaus-Kin** [comment]
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022

**Comment by veezean** [comment]
please upgrade to the latest version and try again...
